repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        # Use Black defaults (line-length=88) to match GitHub Actions

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: black-check
        name: Black format check
        entry: black
        language: system
        args: [--check, .]
        pass_filenames: false
      - id: flake8-check
        name: Flake8 lint check
        entry: flake8
        language: system
        args: [--max-line-length=88, .]
        pass_filenames: false